server:
  port: 8765

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: payment-service-route
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**

        - id: appointment-service-route
          uri: lb://APPOINTMENTSERVICE
          predicates:
            - Path=/appointment/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
