server:
  port: 8085

spring:
  application:
    name: ConfigServer

  cloud:
    config:
      server:
        git:
          uri: https://github.com/gauravk2024/microservice-config
          clone-on-start: true